### ISSUE TITLE
Demo on how to inject style sheets

### ISSUE THREAD

**Issue by jordangotbaum** [Microsoft/react-popout-component#11]
Hi guys,

Great library, but I have no idea how to inject my stylesheet into this bad boy. Is there any chance you could make a demo or just reply here with how to inject your stylesheet or some style elements into the Popout?

Thanks

**Comment by Lego6245** [comment]
TL;DR you should see all styles embedded in your main window copied over to the child window. As long as you're providing a base HTML template, there's nothing to configure.

**Comment by kenotron** [comment]
I think @Lego6245 's answer is pretty comprehensive. The pattern here is that the code in the main window would get loaded there from something like style-loader (webpack plugin), then it would get injected in child window by way of mutation observer. So, no action is needed. The initial styles are also copied over for you as well. So it's pretty minimal what you have to do. If you find that it isn't doing that, please open a bug for us with a small repro.
