### ISSUE TITLE
min-width of body tag in CSS rule is copied to popout window

### ISSUE THREAD

**Issue by JiuqingSong** [Microsoft/react-popout-component#2]
When there is CSS rule for <BODY> tag such as min-width, they are copied to popout window, which causes then min width of popout window is wrong.

**Comment by kenotron** [comment]
The fix in the case is to allow for a class name to be placed in the PopOut component so that such a rule can be overridden.

**Comment by kenotron** [comment]
So, in thinking about #1, I think we can lump those together. It would be the consumer's choice to override the html in general and to override the body with a more specific class so that it could override the min-width css.
