### ISSUE TITLE
Cannot compile with typescript starter

### ISSUE THREAD

**Issue by cetra3** [Microsoft/react-popout-component#4]
While there are typings for all the `lib` files, the `index.js` file doesn't have a corresponding `index.d.ts` file which causes the readme example code to fail.

## Steps to replicate:
* Use the [react typescript](https://github.com/wmonk/create-react-app-typescript) starter to create a react app:
```
create-react-app my-app --scripts-version=react-scripts-ts
```

* Install this module via yarn:

```
yarn add react-popout-component
```

* Cut and paste the App.tsx from the readme

* Try running `yarn start`

### Expected Result

The module compiles correctly and you can run the example

### Actual Result

The module does not compile and errors out:

```
Failed to compile.

./src/App.tsx
(2,22): error TS7016: Could not find a declaration file for module 'react-popout-component'. '/Users/cetra/Desktop/my-app/node_modules/react-popout-component/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-popout-component` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-popout-component';`
```

**Comment by kenotron** [comment]
Good call. This is needed for strict mode (which is the default for the typescript starter!)
